version: '3.10'
services:
  s_backup_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    env_file:
      - .env  # Подключение .env файла
    volumes:
      - ./:/app
      - "/:/host_root" # Примонтировать корневую директорию сервера
    environment:
      DATABASE_URI: ${DB_DSN}
    depends_on:
      - migrations
    restart: always
