"""initial

Revision ID: cb669ef183ff
Revises: 
Create Date: 2024-09-04 22:11:09.669663

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cb669ef183ff"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "s3_storages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=False),
        sa.Column("access_key", sa.String(length=255), nullable=False),
        sa.Column("secret_key", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_s3storage_name", "s3_storages", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_s3_storages_name"), "s3_storages", ["name"], unique=False
    )
    op.create_table(
        "buckets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("storage_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["storage_id"], ["s3_storages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "backup_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("storage_id", sa.Integer(), nullable=False),
        sa.Column("bucket_id", sa.Integer(), nullable=False),
        sa.Column("path", sa.String(length=255), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("file_time", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["bucket_id"], ["buckets.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["storage_id"], ["s3_storages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_bucket_file_name",
        "backup_files",
        ["storage_id", "bucket_id", "path", "file_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_bucket_file_name", table_name="backup_files")
    op.drop_table("backup_files")
    op.drop_table("buckets")
    op.drop_index(op.f("ix_s3_storages_name"), table_name="s3_storages")
    op.drop_index("idx_s3storage_name", table_name="s3_storages")
    op.drop_table("s3_storages")
    # ### end Alembic commands ###
